"""
Regression tests for the technical SEO foundation: unique per-page
metadata (title/description/canonical/robots/Open-Graph/Twitter) for the
three public indexable pages (/, /lead-bot, /compare), homepage
Organization + WebSite JSON-LD, the noindex response header applied to
every non-public route via app.seo_meta.should_apply_noindex_header(),
and /robots.txt + /sitemap.xml.

All metadata is generated by app.seo_meta -- a single reusable module --
rather than duplicated across the two Jinja templates (index.html,
compare.html) and the hand-built HTML string in
agents/lead_dashboard_agent.py's render_lead_dashboard(). These tests
exercise the real rendered output via FastAPI's TestClient, not just the
seo_meta module in isolation, so a future edit that breaks the wiring
(not just the content) will be caught.

Does not touch Lead Finder scanning, DataForSEO, scoring, exports, guest
limits, or CSRF behavior -- purely additive metadata/markup and a response
header.
"""

import re
import sys
import unittest
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

import os
os.environ.setdefault("OPENAI_API_KEY", "test-placeholder-not-a-real-key")

from fastapi.testclient import TestClient

import app.main as appmain
import app.seo_meta as seo_meta

CANONICAL_RE = re.compile(r'rel="canonical" href="([^"]+)"')
TITLE_RE = re.compile(r"<title>([^<]*)</title>")


class PublicPageMetadataTests(unittest.TestCase):
    """Each public page must render exactly one of every
    required tag, with the exact required title/description/canonical."""

    EXPECTED = {
        "/": {
            "title": "LeadMeLeads — Find Local Leads Worth Contacting",
            "description": (
                "Find local business leads by keyword and location. Review "
                "website gaps, contact details, and clear reasons each lead "
                "may be worth contacting."
            ),
            "canonical": "https://leadmeleads.com/",
        },
        "/lead-bot": {
            "title": "Local Lead Finder | LeadMeLeads",
            "description": (
                "Find local business leads by keyword and location, review "
                "contact details, and prioritize businesses worth contacting."
            ),
            "canonical": "https://leadmeleads.com/lead-bot",
        },
        "/compare": {
            "title": "Website SEO Comparison Tool | LeadMeLeads",
            "description": (
                "Compare two websites and uncover practical SEO "
                "opportunities, missing page elements, and clear "
                "recommendations in minutes."
            ),
            "canonical": "https://leadmeleads.com/compare",
        },
        "/what-makes-a-good-lead": {
            "title": "What Makes a Good Lead? A Practical Guide | LeadMeLeads",
            "description": (
                "Learn what makes a good lead, how to identify businesses "
                "worth contacting, and why quality matters more than "
                "collecting more names."
            ),
            "canonical": "https://leadmeleads.com/what-makes-a-good-lead",
        },
        "/how-to-find-local-business-leads-without-buying-a-lead-list": {
            "title": "Find Local Business Leads Without Buying a List | LeadMeLeads",
            "description": (
                "Learn how to find local business leads without buying a list. "
                "Search by keyword and location, review public details, and "
                "verify prospects before outreach."
            ),
            "canonical": (
                "https://leadmeleads.com/"
                "how-to-find-local-business-leads-without-buying-a-lead-list"
            ),
        },
        "/how-to-verify-local-business-leads-before-outreach": {
            "title": "Verify Local Business Leads Before Outreach | LeadMeLeads",
            "description": (
                "Learn how to verify local business leads before outreach by "
                "checking business status, websites, contact details, "
                "locations, and visible opportunities."
            ),
            "canonical": (
                "https://leadmeleads.com/"
                "how-to-verify-local-business-leads-before-outreach"
            ),
        },
        "/how-to-find-local-leads": {
            "title": "How to Find Local Leads: A Step-by-Step Process | LeadMeLeads",
            "description": (
                "Learn how to find local businesses worth reviewing, check "
                "contact details and website signals, and organize prospects "
                "before outreach."
            ),
            "canonical": "https://leadmeleads.com/how-to-find-local-leads",
        },
        "/local-lead-generation": {
            "title": "Local Lead Generation: A Practical Guide for Finding Prospects",
            "description": (
                "Compare practical local lead generation methods, from referrals "
                "and directories to search-based prospect research for outbound "
                "outreach."
            ),
            "canonical": "https://leadmeleads.com/local-lead-generation",
        },
        "/lead-list-vs-lead-finder": {
            "title": "Lead Lists vs Lead Finders: Which Is Better for Prospecting?",
            "description": (
                "Compare purchased lead lists with active lead finders across "
                "freshness, targeting, contact data, research time, and prospect "
                "relevance."
            ),
            "canonical": "https://leadmeleads.com/lead-list-vs-lead-finder",
        },
        "/how-to-find-website-seo-opportunities-in-a-lead-list": {
            "title": (
                "How to Find Website and SEO Opportunities in a Local Lead List | "
                "LeadMeLeads"
            ),
            "description": (
                "A practical framework for auditing a local lead list to spot "
                "website and SEO gaps worth prioritizing before outreach."
            ),
            "canonical": (
                "https://leadmeleads.com/"
                "how-to-find-website-seo-opportunities-in-a-lead-list"
            ),
        },
        "/check-contactability-local-business-leads": {
            "title": (
                "How to Check for Contactability in Local Business Leads | "
                "LeadMeLeads"
            ),
            "description": (
                "A practical, diagnostic guide to checking contactability in "
                "local business leads so you can prioritize outreach and "
                "research using observable contact signals."
            ),
            "canonical": (
                "https://leadmeleads.com/"
                "check-contactability-local-business-leads"
            ),
        },
        "/resources": {
            "title": "Lead Generation Resources | LeadMeLeads",
            "description": (
                "Explore practical guides to finding, reviewing, and organizing "
                "local business prospects for thoughtful outreach."
            ),
            "canonical": "https://leadmeleads.com/resources",
        },
    }

    @classmethod
    def setUpClass(cls):
        cls.client = TestClient(appmain.app)

    def test_each_public_page_returns_200(self):
        for path in self.EXPECTED:
            with self.subTest(path=path):
                response = self.client.get(path)
                self.assertEqual(response.status_code, 200)

    def test_exact_title_per_page(self):
        for path, expected in self.EXPECTED.items():
            with self.subTest(path=path):
                body = self.client.get(path).text
                match = TITLE_RE.search(body)
                self.assertIsNotNone(match, f"no <title> found for {path}")
                self.assertEqual(match.group(1), expected["title"])

    def test_titles_are_pairwise_unique(self):
        titles = [
            TITLE_RE.search(self.client.get(path).text).group(1)
            for path in self.EXPECTED
        ]
        self.assertEqual(len(titles), len(set(titles)))

    def test_exact_meta_description_per_page(self):
        for path, expected in self.EXPECTED.items():
            with self.subTest(path=path):
                body = self.client.get(path).text
                self.assertIn(
                    f'name="description" content="{expected["description"]}"',
                    body,
                )

    def test_descriptions_are_pairwise_unique(self):
        descriptions = [expected["description"] for expected in self.EXPECTED.values()]
        self.assertEqual(len(descriptions), len(set(descriptions)))

    def test_exact_self_referencing_canonical_per_page(self):
        for path, expected in self.EXPECTED.items():
            with self.subTest(path=path):
                body = self.client.get(path).text
                match = CANONICAL_RE.search(body)
                self.assertIsNotNone(match, f"no canonical link found for {path}")
                self.assertEqual(match.group(1), expected["canonical"])

    def test_canonicals_are_pairwise_unique(self):
        canonicals = [expected["canonical"] for expected in self.EXPECTED.values()]
        self.assertEqual(len(canonicals), len(set(canonicals)))

    def test_no_canonical_ever_points_at_localhost_or_loopback(self):
        for path in self.EXPECTED:
            body = self.client.get(path).text
            match = CANONICAL_RE.search(body)
            canonical = match.group(1)
            self.assertNotIn("localhost", canonical)
            self.assertNotIn("127.0.0.1", canonical)
            self.assertTrue(canonical.startswith("https://leadmeleads.com/"))

    def test_meta_robots_is_index_follow_on_public_pages(self):
        for path in self.EXPECTED:
            with self.subTest(path=path):
                body = self.client.get(path).text
                self.assertIn('name="robots" content="index, follow"', body)

    def test_no_x_robots_tag_header_on_public_pages(self):
        for path in self.EXPECTED:
            with self.subTest(path=path):
                response = self.client.get(path)
                self.assertIsNone(response.headers.get("x-robots-tag"))

    def test_no_duplicate_metadata_tags_on_any_public_page(self):
        tag_patterns = [
            "<title>",
            'name="description"',
            'rel="canonical"',
            'name="robots"',
            'property="og:title"',
            'property="og:description"',
            'property="og:url"',
            'property="og:type"',
            'property="og:site_name"',
            'name="twitter:card"',
            'name="twitter:title"',
            'name="twitter:description"',
        ]
        for path in self.EXPECTED:
            body = self.client.get(path).text
            for tag in tag_patterns:
                with self.subTest(path=path, tag=tag):
                    self.assertEqual(body.count(tag), 1)

    def test_open_graph_metadata_matches_title_description_canonical(self):
        for path, expected in self.EXPECTED.items():
            with self.subTest(path=path):
                body = self.client.get(path).text
                self.assertIn(f'property="og:title" content="{expected["title"]}"', body)
                self.assertIn(
                    f'property="og:description" content="{expected["description"]}"',
                    body,
                )
                self.assertIn(f'property="og:url" content="{expected["canonical"]}"', body)
                self.assertIn('property="og:type" content="website"', body)
                self.assertIn('property="og:site_name" content="LeadMeLeads"', body)

    def test_twitter_card_metadata_present(self):
        for path, expected in self.EXPECTED.items():
            with self.subTest(path=path):
                body = self.client.get(path).text
                self.assertIn('name="twitter:card" content="summary_large_image"', body)
                self.assertIn(f'name="twitter:title" content="{expected["title"]}"', body)
                self.assertIn(
                    f'name="twitter:description" content="{expected["description"]}"',
                    body,
                )

    def test_brand_name_is_consistent(self):
        for path in self.EXPECTED:
            body = self.client.get(path).text
            self.assertIn("LeadMeLeads", body)


class HomepageJsonLdTests(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        cls.client = TestClient(appmain.app)

    def test_homepage_has_organization_and_website_jsonld(self):
        import json

        body = self.client.get("/").text
        scripts = re.findall(
            r'<script type="application/ld\+json">(.*?)</script>', body, re.DOTALL
        )
        self.assertEqual(len(scripts), 2)

        types = set()
        for raw in scripts:
            data = json.loads(raw)
            self.assertEqual(data["@context"], "https://schema.org")
            self.assertEqual(data["name"], "LeadMeLeads")
            self.assertEqual(data["url"], "https://leadmeleads.com")
            types.add(data["@type"])

        self.assertEqual(types, {"Organization", "WebSite"})

    def test_homepage_jsonld_has_no_search_action(self):
        body = self.client.get("/").text
        self.assertNotIn("SearchAction", body)

    def test_homepage_jsonld_has_no_unverifiable_claims(self):
        body = self.client.get("/").text
        scripts = re.findall(
            r'<script type="application/ld\+json">(.*?)</script>', body, re.DOTALL
        )
        jsonld_text = " ".join(scripts)
        for forbidden in [
            "aggregateRating",
            "reviewCount",
            "ratingValue",
            "priceRange",
            "foundingDate",
            "sameAs",
            "potentialAction",
        ]:
            self.assertNotIn(forbidden, jsonld_text)

    def test_other_public_pages_do_not_duplicate_homepage_organization_jsonld(self):
        for path in ["/lead-bot", "/compare"]:
            with self.subTest(path=path):
                body = self.client.get(path).text
                self.assertNotIn('"@type":"Organization"', body)
                self.assertNotIn('"@type":"WebSite"', body)


class ProductPageJsonLdTests(unittest.TestCase):
    """/lead-bot and /compare each get exactly one WebApplication JSON-LD
    block, built only from the page's own verified title/description/
    canonical -- no ratings, pricing, or user counts."""

    @classmethod
    def setUpClass(cls):
        cls.client = TestClient(appmain.app)

    EXPECTED = {
        "/lead-bot": {
            "name": seo_meta.LEAD_FINDER_PAGE.title,
            "description": seo_meta.LEAD_FINDER_PAGE.description,
            "url": "https://leadmeleads.com/lead-bot",
        },
        "/compare": {
            "name": seo_meta.COMPARE_PAGE.title,
            "description": seo_meta.COMPARE_PAGE.description,
            "url": "https://leadmeleads.com/compare",
        },
    }

    def test_webapplication_jsonld_present_and_valid(self):
        import json

        for path, expected in self.EXPECTED.items():
            with self.subTest(path=path):
                body = self.client.get(path).text
                scripts = re.findall(
                    r'<script type="application/ld\+json">(.*?)</script>', body, re.DOTALL
                )
                webapp_blocks = []
                for raw in scripts:
                    data = json.loads(raw)
                    if data.get("@type") == "WebApplication":
                        webapp_blocks.append(data)
                self.assertEqual(len(webapp_blocks), 1, f"expected exactly one WebApplication block on {path}")
                data = webapp_blocks[0]
                self.assertEqual(data["@context"], "https://schema.org")
                self.assertEqual(data["name"], expected["name"])
                self.assertEqual(data["description"], expected["description"])
                self.assertEqual(data["url"], expected["url"])

    def test_webapplication_jsonld_has_no_unverifiable_claims(self):
        for path in self.EXPECTED:
            with self.subTest(path=path):
                body = self.client.get(path).text
                for forbidden in [
                    "aggregateRating",
                    "reviewCount",
                    "ratingValue",
                    "offers",
                    "price",
                ]:
                    self.assertNotIn(forbidden, body)


class ArticleJsonLdTests(unittest.TestCase):
    """The four guide pages each get one Article JSON-LD block with no
    fabricated dates, alongside their existing FAQPage block."""

    @classmethod
    def setUpClass(cls):
        cls.client = TestClient(appmain.app)

    ARTICLE_PAGES = {
        "/what-makes-a-good-lead": seo_meta.GOOD_LEAD_PAGE,
        "/how-to-find-local-leads": seo_meta.FIND_LOCAL_LEADS_PAGE,
        "/local-lead-generation": seo_meta.LOCAL_LEAD_GENERATION_PAGE,
        "/lead-list-vs-lead-finder": seo_meta.LEAD_LIST_VS_FINDER_PAGE,
        "/how-to-find-website-seo-opportunities-in-a-lead-list": (
            seo_meta.FIND_WEBSITE_SEO_OPPORTUNITIES_IN_LEAD_LIST_PAGE
        ),
        "/check-contactability-local-business-leads": (
            seo_meta.CHECK_CONTACTABILITY_LOCAL_BUSINESS_LEADS_PAGE
        ),
    }

    def test_article_jsonld_present_and_valid(self):
        import json

        for path, page in self.ARTICLE_PAGES.items():
            with self.subTest(path=path):
                body = self.client.get(path).text
                scripts = re.findall(
                    r'<script type="application/ld\+json">(.*?)</script>', body, re.DOTALL
                )
                article_blocks = [json.loads(raw) for raw in scripts if json.loads(raw).get("@type") == "Article"]
                self.assertEqual(len(article_blocks), 1, f"expected exactly one Article block on {path}")
                data = article_blocks[0]
                self.assertEqual(data["headline"], page.title)
                self.assertEqual(data["description"], page.description)
                self.assertEqual(data["mainEntityOfPage"], seo_meta.canonical_url(page.canonical_path))
                self.assertEqual(data["publisher"]["name"], "LeadMeLeads")

    def test_article_jsonld_has_no_fabricated_dates(self):
        for path in self.ARTICLE_PAGES:
            with self.subTest(path=path):
                body = self.client.get(path).text
                self.assertNotIn("datePublished", body)
                self.assertNotIn("dateModified", body)

    def test_resources_hub_has_no_article_jsonld(self):
        body = self.client.get("/resources").text
        self.assertNotIn('"@type":"Article"', body)


class NoindexPrivateRouteTests(unittest.TestCase):
    """Every non-public route must carry X-Robots-Tag: noindex, nofollow,
    regardless of auth state or response status (redirect, 200, 401,
    etc.) -- the middleware applies unconditionally to non-public paths."""

    @classmethod
    def setUpClass(cls):
        cls.client = TestClient(appmain.app)

    PRIVATE_PATHS = [
        "/login",
        "/create-account",
        "/forgot-password",
        "/settings",
        "/history",
        "/analyze",
        "/lead-bot/run",
        "/lead-bot/csrf-token",
        "/api/find-competitors",
    ]

    def test_private_routes_carry_noindex_header(self):
        for path in self.PRIVATE_PATHS:
            with self.subTest(path=path):
                response = self.client.get(path, follow_redirects=False)
                self.assertEqual(
                    response.headers.get("x-robots-tag"),
                    "noindex, nofollow",
                    f"{path} was not noindexed (status {response.status_code})",
                )

    def test_dynamic_lead_bot_subroutes_are_noindexed_even_though_bare_lead_bot_is_public(self):
        bare = self.client.get("/lead-bot")
        self.assertIsNone(bare.headers.get("x-robots-tag"))

        sub = self.client.get("/lead-bot/live-status/does-not-exist", follow_redirects=False)
        self.assertEqual(sub.headers.get("x-robots-tag"), "noindex, nofollow")

    def test_static_assets_are_never_noindexed(self):
        response = self.client.get("/static/logo.png")
        self.assertIsNone(response.headers.get("x-robots-tag"))

    def test_a_brand_new_unlisted_dynamic_route_is_noindexed_by_default(self):
        """The middleware is deny-listed on the public allowlist, not an
        allow-list of known private routes -- so a route this test suite
        has never heard of is still noindexed just by not being public."""
        response = self.client.get("/some/totally/new/route/nobody/registered", follow_redirects=False)
        self.assertEqual(response.headers.get("x-robots-tag"), "noindex, nofollow")


class RobotsTxtTests(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        cls.client = TestClient(appmain.app)

    def test_robots_txt_returns_200_plain_text(self):
        response = self.client.get("/robots.txt")
        self.assertEqual(response.status_code, 200)
        self.assertIn("text/plain", response.headers.get("content-type", ""))

    def test_robots_txt_references_the_sitemap(self):
        body = self.client.get("/robots.txt").text
        self.assertIn("Sitemap: https://leadmeleads.com/sitemap.xml", body)

    def test_robots_txt_does_not_disallow_the_three_public_pages(self):
        body = self.client.get("/robots.txt").text
        lines = [line.strip() for line in body.splitlines() if line.strip().lower().startswith("disallow:")]
        for path in seo_meta.PUBLIC_INDEXABLE_PATHS:
            for line in lines:
                disallowed_prefix = line.split(":", 1)[1].strip()
                self.assertFalse(
                    path == disallowed_prefix or (disallowed_prefix and path.startswith(disallowed_prefix) and disallowed_prefix != "/"),
                    f"robots.txt line {line!r} would block public page {path!r}",
                )

    def test_robots_txt_does_not_disallow_static_assets(self):
        body = self.client.get("/robots.txt").text
        self.assertNotIn("Disallow: /static", body)

    def test_robots_txt_disallows_known_private_prefixes(self):
        body = self.client.get("/robots.txt").text
        for expected in [
            "Disallow: /login",
            "Disallow: /settings",
            "Disallow: /history",
            "Disallow: /admin",
            "Disallow: /lead-bot/",
            "Disallow: /reports/",
        ]:
            self.assertIn(expected, body)

    def test_robots_txt_exposes_no_secrets_or_filesystem_paths(self):
        body = self.client.get("/robots.txt").text
        for forbidden in ["/home/", "/var/www", ".env", "DATAFORSEO", "SECRET", "PASSWORD"]:
            self.assertNotIn(forbidden, body)

    def test_robots_txt_has_no_noindex_header(self):
        response = self.client.get("/robots.txt")
        self.assertIsNone(response.headers.get("x-robots-tag"))


class SitemapXmlTests(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        cls.client = TestClient(appmain.app)

    def test_sitemap_returns_200_xml(self):
        response = self.client.get("/sitemap.xml")
        self.assertEqual(response.status_code, 200)
        self.assertIn("xml", response.headers.get("content-type", ""))

    def test_sitemap_contains_exactly_the_intended_pages(self):
        body = self.client.get("/sitemap.xml").text
        urls = re.findall(r"<loc>([^<]+)</loc>", body)
        self.assertEqual(
            set(urls),
            {
                "https://leadmeleads.com/",
                "https://leadmeleads.com/lead-bot",
                "https://leadmeleads.com/compare",
                "https://leadmeleads.com/what-makes-a-good-lead",
                "https://leadmeleads.com/how-to-find-local-leads",
                "https://leadmeleads.com/how-to-find-local-business-leads-without-buying-a-lead-list",
                "https://leadmeleads.com/how-to-verify-local-business-leads-before-outreach",
                "https://leadmeleads.com/local-lead-generation",
                "https://leadmeleads.com/lead-list-vs-lead-finder",
                "https://leadmeleads.com/how-to-find-website-seo-opportunities-in-a-lead-list",
                "https://leadmeleads.com/check-contactability-local-business-leads",
                "https://leadmeleads.com/resources",
            },
        )
        self.assertEqual(len(urls), 12)

    def test_sitemap_has_no_fabricated_lastmod(self):
        body = self.client.get("/sitemap.xml").text
        self.assertNotIn("<lastmod>", body)

    def test_sitemap_urls_match_public_indexable_paths_constant(self):
        """Locks sitemap.xml to the same single source of truth used by
        the noindex middleware, so they can never silently drift apart."""
        body = self.client.get("/sitemap.xml").text
        urls = set(re.findall(r"<loc>([^<]+)</loc>", body))
        expected = {seo_meta.canonical_url(path) for path in seo_meta.PUBLIC_INDEXABLE_PATHS}
        self.assertEqual(urls, expected)

    def test_sitemap_has_no_noindex_header(self):
        """Regression guard: /sitemap.xml is a crawler-control file, not
        a page, and must never be noindexed -- a crawler that respects
        X-Robots-Tag would otherwise ignore the sitemap entirely."""
        response = self.client.get("/sitemap.xml")
        self.assertIsNone(response.headers.get("x-robots-tag"))


class SeoMetaModuleUnitTests(unittest.TestCase):
    """Direct unit coverage of app.seo_meta, independent of the running
    app, for fast failure localization."""

    def test_canonical_url_strips_trailing_slash_except_root(self):
        self.assertEqual(seo_meta.canonical_url("/"), "https://leadmeleads.com/")
        self.assertEqual(seo_meta.canonical_url("/lead-bot"), "https://leadmeleads.com/lead-bot")

    def test_should_apply_noindex_header_public_paths_false(self):
        for path in seo_meta.PUBLIC_INDEXABLE_PATHS:
            self.assertFalse(seo_meta.should_apply_noindex_header(path))

    def test_should_apply_noindex_header_static_assets_false(self):
        self.assertFalse(seo_meta.should_apply_noindex_header("/static/anything.js"))

    def test_should_apply_noindex_header_crawler_control_paths_false(self):
        for path in seo_meta.CRAWLER_CONTROL_PATHS:
            with self.subTest(path=path):
                self.assertFalse(seo_meta.should_apply_noindex_header(path))

    def test_should_apply_noindex_header_everything_else_true(self):
        for path in ["/login", "/settings", "/history", "/lead-bot/run", "/random-new-route"]:
            with self.subTest(path=path):
                self.assertTrue(seo_meta.should_apply_noindex_header(path))


class AuthAndPrivatePageNoindexMetaTagTests(unittest.TestCase):
    """Belt-and-suspenders: private HTML pages carry an explicit
    <meta name="robots" content="noindex, nofollow"> tag in addition to
    the X-Robots-Tag header the middleware already applies to every
    non-public route."""

    @classmethod
    def setUpClass(cls):
        cls.client = TestClient(appmain.app)

    def test_login_page_has_noindex_meta(self):
        body = self.client.get("/login").text
        self.assertIn('<meta name="robots" content="noindex, nofollow">', body)

    def test_create_account_page_has_noindex_meta(self):
        body = self.client.get("/create-account").text
        self.assertIn('<meta name="robots" content="noindex, nofollow">', body)

    def test_forgot_password_page_has_noindex_meta(self):
        body = self.client.get("/forgot-password").text
        self.assertIn('<meta name="robots" content="noindex, nofollow">', body)

    def test_reset_password_invalid_link_page_has_noindex_meta(self):
        response = self.client.get("/reset-password", params={"token": "not-a-real-token"})
        self.assertIn('<meta name="robots" content="noindex, nofollow">', response.text)


class InternalLinkTests(unittest.TestCase):
    """Contextual internal links required by the launch-foundation task
    that weren't already covered by the shared public_guide_base.html
    template (Lead Finder -> resources, Compare -> Lead Finder + resources)."""

    @classmethod
    def setUpClass(cls):
        cls.client = TestClient(appmain.app)

    def test_lead_finder_links_to_resources(self):
        body = self.client.get("/lead-bot").text
        self.assertIn('href="/resources"', body)

    def test_lead_finder_links_to_what_makes_a_good_lead(self):
        body = self.client.get("/lead-bot").text
        self.assertIn('href="/what-makes-a-good-lead"', body)

    def test_compare_links_to_resources_and_lead_finder(self):
        body = self.client.get("/compare").text
        self.assertIn('href="/resources"', body)
        self.assertIn('href="/lead-bot"', body)


class NotFoundPageTests(unittest.TestCase):
    """Unmatched routes return an actual 404 (not 200) with a branded
    HTML page containing safe navigation links, no stack traces, and no
    internal filesystem paths."""

    @classmethod
    def setUpClass(cls):
        cls.client = TestClient(appmain.app)

    def test_unknown_route_returns_404(self):
        response = self.client.get("/this-route-does-not-exist")
        self.assertEqual(response.status_code, 404)

    def test_unknown_route_returns_html_not_json(self):
        response = self.client.get("/this-route-does-not-exist")
        self.assertIn("text/html", response.headers.get("content-type", ""))

    def test_404_page_has_safe_navigation_links(self):
        body = self.client.get("/this-route-does-not-exist").text
        for expected_href in ['href="/"', 'href="/lead-bot"', 'href="/compare"', 'href="/resources"']:
            with self.subTest(href=expected_href):
                self.assertIn(expected_href, body)

    def test_404_page_is_noindexed(self):
        response = self.client.get("/this-route-does-not-exist")
        self.assertIn('<meta name="robots" content="noindex, nofollow">', response.text)
        self.assertEqual(response.headers.get("x-robots-tag"), "noindex, nofollow")

    def test_404_page_exposes_no_stack_trace_or_internal_paths(self):
        body = self.client.get("/this-route-does-not-exist").text
        for forbidden in ["Traceback", "/home/", "/mnt/", "/var/www", "app/main.py", "File \""]:
            self.assertNotIn(forbidden, body)

    def test_other_http_exceptions_are_unaffected(self):
        """A non-404 HTTPException (405 Method Not Allowed, raised by
        Starlette's router for a real route hit with the wrong verb) must
        keep FastAPI's default JSON error format, not the new branded
        404 page -- the custom handler only special-cases status 404."""
        response = self.client.post("/robots.txt")
        self.assertEqual(response.status_code, 405)
        self.assertNotIn("notfound-card", response.text)


if __name__ == "__main__":
    unittest.main()
